### ISSUE TITLE
No work 

### ISSUE THREAD

**Issue by minehostil** [Keurig-Creator/XPBooster#1]
Hello I have this problem
Purpur 1.20.4
Java 17
![Screenshot_20240615-015236_Chrome](https://github.com/Keurig-Creator/XPBooster/assets/108409110/5772dd94-a98f-4dc8-9b70-8f4e26e24b6b)

**Comment by dentatar** [comment]
Hello, same problem here… Full error:
```
[20:54:47 ERROR]: [DirectoryProviderSource] Error preparing plugin context: Directory 'plugins/XPBooster-1.3.jar' failed to update!
java.lang.RuntimeException: Directory 'plugins/XPBooster-1.3.jar' failed to update!
	at io.papermc.paper.plugin.provider.source.FileProviderSource.prepareContext(FileProviderSource.java:51) ~[paper-1.20.4.jar:git-Paper-497]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$prepareContext$1(DirectoryProviderSource.java:33) ~[paper-1.20.4.jar:git-Paper-497]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.walkFiles(DirectoryProviderSource.java:59) ~[paper-1.20.4.jar:git-Paper-497]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.prepareContext(DirectoryProviderSource.java:31) ~[paper-1.20.4.jar:git-Paper-497]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.prepareContext(DirectoryProviderSource.java:17) ~[paper-1.20.4.jar:git-Paper-497]
	at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[paper-1.20.4.jar:git-Paper-497]
	at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:101) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.Main.main(Main.java:120) ~[paper-1.20.4.jar:git-Paper-497]
	at org.bukkit.craftbukkit.Main.main(Main.java:326) ~[paper-1.20.4.jar:git-Paper-497]
	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: plugins/XPBooster-1.3.jar does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
	at io.papermc.paper.plugin.provider.source.FileProviderSource.checkUpdate(FileProviderSource.java:109) ~[paper-1.20.4.jar:git-Paper-497]
	at io.papermc.paper.plugin.provider.source.FileProviderSource.prepareContext(FileProviderSource.java:49) ~[paper-1.20.4.jar:git-Paper-497]
	... 21 more
Caused by: java.lang.IllegalArgumentException: plugins/XPBooster-1.3.jar does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
	at io.papermc.paper.plugin.provider.source.FileProviderSource.getPluginName(FileProviderSource.java:118) ~[paper-1.20.4.jar:git-Paper-497]
	at io.papermc.paper.plugin.provider.source.FileProviderSource.checkUpdate(FileProviderSource.java:90) ~[paper-1.20.4.jar:git-Paper-497]
	at io.papermc.paper.plugin.provider.source.FileProviderSource.prepareContext(FileProviderSource.java:49) ~[paper-1.20.4.jar:git-Paper-497]
	... 21 more
```

Version 1.2 works tho

**Comment by Keurig-Creator** [comment]
Okay this issue is now resolved in new update.
