### ISSUE TITLE
Not working with NullPointerException

### ISSUE THREAD

**Issue by dentatar** [Keurig-Creator/XPBooster#2]
Hello, it's not working on Paper 1.20.4 build 497 with the following error:
```
[06:16:19 ERROR]: Could not pass event PlayerExpChangeEvent to XPBooster v1.3.1
java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()" because the return value of "java.util.HashMap.get(Object)" is null
	at com.keurigsweb.xpbooster.listener.PlayerExpChangeListener.onExperienceChange(PlayerExpChangeListener.java:47) ~[XPBooster-1.3.1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor21.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-497]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-497]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-497]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerExpChangeEvent(CraftEventFactory.java:1302) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.world.entity.ExperienceOrb.playerTouch(ExperienceOrb.java:322) ~[?:?]
	at net.minecraft.world.entity.player.Player.touch(Player.java:635) ~[?:?]
	at net.minecraft.world.entity.player.Player.aiStep(Player.java:605) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3066) ~[?:?]
	at net.minecraft.world.entity.player.Player.tick(Player.java:274) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:770) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:338) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:593) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1746) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1525) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-497]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

**Comment by Keurig-Creator** [comment]
Could you explain how this occurs? I cannot seem to reproduce this error, thank you!

**Comment by dentatar** [comment]
Huh? Sorry but i can't either, just played with plugins on a testing server and maybe did something wrong 🤔 I will reopen with reproduction steps if it happens again then…
